// Zen R4 bring-up: exercise every header-exposed FPGA GPIO.
// Generated by gen_zen.py -- do not edit by hand.
//
// Patterns cycle automatically:
//   0  walking one    -- identify each pin individually
//   1  walking zero   -- same, inverted (catches stuck-high)
//   2  even/odd split -- catches shorts between adjacent pins
//   3  all blink      -- quick visual / current draw check
//
// SAFE_MODE=1 holds the config-strap / dual-function pins static low.

`default_nettype none

module blink #(
    parameter SAFE_MODE = 1,
    parameter CLK_HZ    = 50000000,
    parameter STEP_HZ   = 5
) (
    input  wire clk,
    output wire led,        // F3  IOL_11
    output wire led2,       // G1  IOL_12
    output wire led3,       // F1  IOL_13
    output wire led4,       // E2  IOL_14
    output wire led5,       // E1  IOL_15
    output wire led6,       // C2  IOL_16
    output wire led7,       // D2  IOL_17
    output wire led8,       // E3  IOL_18
    output wire led9,       // D3  IOL_19
    output wire led10,      // B3  IOL_21
    output wire led11,      // A5  IOR_00
    output wire led12,      // B5  IOR_01
    output wire led13,      // C5  IOR_02
    output wire led14,      // A6  IOR_03
    output wire led15,      // B6  IOR_05
    output wire led16,      // C6  IOR_06
    output wire led17,      // C7  IOR_07
    output wire led18,      // A8  IOR_08
    output wire led19,      // A9  IOR_10
    output wire led20,      // B8  IOR_11
    output wire led21,      // C8  IOR_12
    output wire led22,      // D6  IOR_13
    output wire led23,      // B9  IOR_14
    output wire led24,      // D8  IOR_17
    output wire led25,      // D9  IOR_18
    output wire led26,      // E8  IOR_19
    output wire led27,      // F8  IOR_20
    output wire led28,      // E7  IOR_21
    output wire led29,      // F7  IOR_22
    output wire led30,      // E6  IOR_23
    output wire led31,      // F6  IOR_24
    output wire led32,      // F5  IOR_25
    output wire led33,      // G9  IOR_26
    output wire led34,      // H9  IOR_27
    output wire led35,      // J9  IOR_28
    output wire led36,      // J8  IOR_30
    output wire led37,      // G8  IOR_31
    output wire led38,      // H8  IOR_32
    output wire led39,      // J7  IOR_34
    output wire led40,      // G6  IOR_35
    output wire led41,      // H6  IOR_36
    output wire led42,      // C9  IOR_15
    output wire led43,       // D7  IOR_16
    output wire led44
);

    localparam N = 44;

    // Pins to hold static when SAFE_MODE=1 (config straps, reserved, NSTATUS).
    localparam [N-1:0] FLAGGED = {
        1'b0,     // led43  IOR_16  D6 green LED / CBUS1 / btn
        1'b0,     // led42  IOR_15  D2 blue LED / CBUS0 / btn
        1'b0,     // led41  IOR_36
        1'b0,     // led40  IOR_35  CSO at config
        1'b0,     // led39  IOR_34  CSI at config
        1'b0,     // led38  IOR_32
        1'b0,     // led37  IOR_31
        1'b0,     // led36  IOR_30
        1'b0,     // led35  IOR_28
        1'b0,     // led34  IOR_27
        1'b0,     // led33  IOR_26  CBSEL0 at config
        1'b0,     // led32  IOR_25
        1'b0,     // led31  IOR_24
        1'b0,     // led30  IOR_23  CTRL4
        1'b0,     // led29  IOR_22  CTRL5
        1'b0,     // led28  IOR_21  CBSEL1 at config
        1'b0,     // led27  IOR_20  CLK-capable
        1'b0,     // led26  IOR_19  CLK-capable
        1'b0,     // led25  IOR_18  CLK-capable
        1'b0,     // led24  IOR_17  CBUS2 at config
        1'b0,     // led23  IOR_14
        1'b0,     // led22  IOR_13
        1'b0,     // led21  IOR_12
        1'b0,     // led20  IOR_11
        1'b0,     // led19  IOR_10
        1'b0,     // led18  IOR_08
        1'b0,     // led17  IOR_07
        1'b0,     // led16  IOR_06
        1'b0,     // led15  IOR_05
        1'b0,     // led14  IOR_03
        1'b0,     // led13  IOR_02  RESERVED_OUT
        1'b0,     // led12  IOR_01
        1'b0,     // led11  IOR_00
        1'b0,     // led10  IOL_21  also NSTATUS
        1'b0,     // led9   IOL_19  CTRL3
        1'b0,     // led8   IOL_18  CTRL2
        1'b0,     // led7   IOL_17  CLK-capable
        1'b0,     // led6   IOL_16  CLK-capable
        1'b0,     // led5   IOL_15  CLK-capable
        1'b0,     // led4   IOL_14  CLK-capable
        1'b0,     // led3   IOL_13  CTRL1
        1'b0,     // led2   IOL_12  CTRL0
        1'b0,      // led    IOL_11
        1'b0
    };

    localparam integer DIV = CLK_HZ / STEP_HZ;

    reg [31:0] tick   = 32'd0;
    reg [7:0]  idx    = 8'd0;
    reg [1:0]  mode   = 2'd0;
    reg [N-1:0] pat   = {N{1'b0}};

    always @(posedge clk) begin
        if (tick == DIV[31:0] - 1) begin
            tick <= 32'd0;
            if (idx == N - 1) begin
                idx  <= 8'd0;
                mode <= mode + 2'd1;
            end else begin
                idx <= idx + 8'd1;
            end
        end else begin
            tick <= tick + 32'd1;
        end
    end

    integer k;
    always @(posedge clk) begin
        case (mode)
            2'd0: begin                       // walking one
                for (k = 0; k < N; k = k + 1)
                    pat[k] <= (k[7:0] == idx);
            end
            2'd1: begin                       // walking zero
                for (k = 0; k < N; k = k + 1)
                    pat[k] <= ~(k[7:0] == idx);
            end
            2'd2: begin                       // even / odd
                for (k = 0; k < N; k = k + 1)
                    pat[k] <= (k[0] ^ idx[0]);
            end
            default: begin                    // all together
                pat <= {N{idx[0]}};
            end
        endcase
    end

    wire [N-1:0] drv = SAFE_MODE ? (pat & ~FLAGGED) : pat;

    assign led    = drv[0];       // F3  IOL_11
    assign led2   = drv[1];       // G1  IOL_12
    assign led3   = drv[2];       // F1  IOL_13
    assign led4   = drv[3];       // E2  IOL_14
    assign led5   = drv[4];       // E1  IOL_15
    assign led6   = drv[5];       // C2  IOL_16
    assign led7   = drv[6];       // D2  IOL_17
    assign led8   = drv[7];       // E3  IOL_18
    assign led9   = drv[8];       // D3  IOL_19
    assign led10  = drv[9];       // B3  IOL_21
    assign led11  = drv[10];      // A5  IOR_00
    assign led12  = drv[11];      // B5  IOR_01
    assign led13  = drv[12];      // C5  IOR_02
    assign led14  = drv[13];      // A6  IOR_03
    assign led15  = drv[14];      // B6  IOR_05
    assign led16  = drv[15];      // C6  IOR_06
    assign led17  = drv[16];      // C7  IOR_07
    assign led18  = drv[17];      // A8  IOR_08
    assign led19  = drv[18];      // A9  IOR_10
    assign led20  = drv[19];      // B8  IOR_11
    assign led21  = drv[20];      // C8  IOR_12
    assign led22  = drv[21];      // D6  IOR_13
    assign led23  = drv[22];      // B9  IOR_14
    assign led24  = drv[23];      // D8  IOR_17
    assign led25  = drv[24];      // D9  IOR_18
    assign led26  = drv[25];      // E8  IOR_19
    assign led27  = drv[26];      // F8  IOR_20
    assign led28  = drv[27];      // E7  IOR_21
    assign led29  = drv[28];      // F7  IOR_22
    assign led30  = drv[29];      // E6  IOR_23
    assign led31  = drv[30];      // F6  IOR_24
    assign led32  = drv[31];      // F5  IOR_25
    assign led33  = drv[32];      // G9  IOR_26
    assign led34  = drv[33];      // H9  IOR_27
    assign led35  = drv[34];      // J9  IOR_28
    assign led36  = drv[35];      // J8  IOR_30
    assign led37  = drv[36];      // G8  IOR_31
    assign led38  = drv[37];      // H8  IOR_32
    assign led39  = drv[38];      // J7  IOR_34
    assign led40  = drv[39];      // G6  IOR_35
    assign led41  = drv[40];      // H6  IOR_36
    assign led42  = drv[41];      // C9  IOR_15
    assign led43  = drv[42];      // D7  IOR_16
    assign led44  = drv[43];

endmodule

`default_nettype wire